### ISSUE TITLE
The NAS folder : "human-ai-dialog/vilbert/data2" 

### ISSUE THREAD

**Issue by kelikeli** [ThalesGroup/ConceptBERT#2]
I did not find this file in your project. Can you provide the data and pre_trained model of this file?
Looking forward to your reply, thank you！

**Comment by marlenegautier** [comment]
Hello, 
`vilbert/data2` are folder and subfolder where the dataset are located.
You can download them here:

* VQA2.0 dataset: https://visualqa.org/download.html
* OKVQA dataset: https://okvqa.allenai.org/download.html
* ConceptualCaptions dataset: https://ai.google.com/research/ConceptualCaptions/download

Our team is working to share the files requested in the issues and as soon as the files are ready we will share them with you  (this includes the file model_9.bin)

**Comment by marlenegautier** [comment]
Hello, thank you for your patience and sorry for the late reply, the `pre-trained model` (model_9.bin) is available on the kaggle of the project: https://www.kaggle.com/thalesgroup/conceptbert/
