### ISSUE TITLE
how to find the data?

### ISSUE THREAD

**Issue by hughjackman111** [ThalesGroup/ConceptBERT#3]
Hi, I try to find the data, but it missed. As the README says" The  data might be saved in a folder along with pretrained_models and organized as shown below: vilbert/data2", but I didn't find the file "data2". So where could I find the dataset?Thanks!

**Comment by marlenegautier** [comment]
Hello, you can download the following datasets at these links:

VQA2.0 dataset: https://visualqa.org/download.html
OKVQA dataset: https://okvqa.allenai.org/download.html
ConceptualCaptions dataset: https://ai.google.com/research/ConceptualCaptions/download

`vilbert/data2` are folder and subfolder where the dataset are located.
