### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by Hoil-Z** [ThalesGroup/ConceptBERT#4]
Hi,I'm trying to run the project , but I don't have the appropriate datasets, could you please upload the datasets or reply me how I can download the datasets? Thanks!!!

**Comment by fgxaos** [comment]
Hi, you can download the following datasets at these links:
- VQA2.0 dataset: https://visualqa.org/download.html
- OKVQA dataset: https://okvqa.allenai.org/download.html
- ConceptualCaptions dataset: https://ai.google.com/research/ConceptualCaptions/download

**Comment by kelikeli** [comment]
> Hi, you can download the following datasets at these links:
> 
> * VQA2.0 dataset: https://visualqa.org/download.html
> * OKVQA dataset: https://okvqa.allenai.org/download.html
> * ConceptualCaptions dataset: https://ai.google.com/research/ConceptualCaptions/download

Hello, can you also provide the pretrained model : --from_pretrained=/nas-data/vilbert/data2/kilbert_base_model/pytorch_model_9.bin?

**Comment by Hoil-Z** [comment]
> Hi, you can download the following datasets at these links:
> 
> * VQA2.0 dataset: https://visualqa.org/download.html
> * OKVQA dataset: https://okvqa.allenai.org/download.html
> * ConceptualCaptions dataset: https://ai.google.com/research/ConceptualCaptions/download

Thank you very much! And the model_9.bin you can provide ?

**Comment by marlenegautier** [comment]
Hello, our team is already working the issues of the project and as soon as the files are ready we will share them with you (this includes the file model_9.bin)

**Comment by marlenegautier** [comment]
Hello, thank you for your patience and sorry for the late reply, the `pre-trained model` (model_9.bin) is available on the kaggle of the project: https://www.kaggle.com/thalesgroup/conceptbert/
