### ISSUE TITLE
Knowledge Graph Embeddings

### ISSUE THREAD

**Issue by petervickers** [ThalesGroup/ConceptBERT#6]
Hello all,

It appears that the code is using the Numberbatch embeddings for the "Conceptual" modality.

In your paper, you suggest using embeddings from the paper 'Commonsense Knowledge Base Completion with Structural and Semantic Context'.

Are there any plans to make these embeddings and associated code public?

Many thanks.

**Comment by marlenegautier** [comment]
Hello, this is the related repository for the embeddings : https://github.com/commonsense/conceptnet-numberbatch
