### ISSUE TITLE
can you upload the original val_result.json file for OKVQA? 

### ISSUE THREAD

**Issue by Ivyzhang1998** [ThalesGroup/ConceptBERT#7]
Hi, it seems that the following validation result file all contains the same answer. Can you upload the. original result file for OKVQA, which gives the 33.04 accuracy? Thanks a lot! https://github.com/ThalesGroup/ConceptBERT/blob/master/kilbert_project/results/OKVQA_model3-kilbert_validation_and_evaluation/val_result.json

**Comment by marlenegautier** [comment]
Hello, our team is already working the issues of the project, and as soon as we have the necessary information we will update the repo.

**Comment by marlenegautier** [comment]
Hello, thank you for your patience and sorry for the late reply, the original `validation file` and the `pre-trained model` are available on the kaggle of the project: https://www.kaggle.com/thalesgroup/conceptbert/

**Comment by Ivyzhang1998** [comment]
Thank you Marlene!
