### ISSUE TITLE
how to build the label2ans dict of OK-VQA

### ISSUE THREAD

**Issue by PamelaDDD** [ThalesGroup/ConceptBERT#8]
Hello sir! Could you tell me how many labels you select of OK-VQA? Did you select top k answers in the ok-vqa dataset as the label set? and how about the K you set?

**Comment by marlenegautier** [comment]
Hello,
> Hello sir! Could you tell me how many labels you select of OK-VQA? 

We use all the labels for OK-VQA

> Did you select top k answers in the ok-vqa dataset as the label set? and how about the K you set?

We use top k answers with the value  `top-1`
